#ifndef DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DIJKSTRA_HPP
#define DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DIJKSTRA_HPP
namespace Test_Dijkstra
{
    void Test();

    void Test1();
}
#endif //DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DIJKSTRA_HPP
