#ifndef DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_UNION_FIND_HPP
#define DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_UNION_FIND_HPP
namespace Test_Union_Find
{
    void Test();

    void Test1();
}
#endif //DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_UNION_FIND_HPP
