#ifndef DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_KRUSKAL_MST_HPP
#define DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_KRUSKAL_MST_HPP
namespace Test_Kruskal_MST
{
    void Test();

    void Test1();
}
#endif //DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_KRUSKAL_MST_HPP
