#ifndef DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DISJOINT_SET_HPP
#define DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DISJOINT_SET_HPP

namespace Test_Disjoint_Set
{
    void Test();

    void Test1();
}
#endif //DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_DISJOINT_SET_HPP
