#ifndef DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_PRIM_MST_HPP
#define DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_PRIM_MST_HPP
namespace Test_Prim_MST
{
    void Test();

    void Test1();
}
#endif //DESIGN_AND_ANALAYSIS_OF_ALGORITHMS_TEST_PRIM_MST_HPP
